name: african_echoes
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.11.2
  auto_route: ^0.6.9
  bloc: ^6.0.1
  cloud_firestore: ^0.14.2
  connectivity: ^0.4.9
  cupertino_icons: ^0.1.2
  disk_space: ^0.0.3
  encrypt: ^4.0.2
  equatable: ^1.2.3
  firebase_analytics: ^6.1.0
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.1
  flushbar: ^1.10.0
  flutter_bloc: ^6.0.1
  flutter_downloader: ^1.4.4
  flutter_facebook_login: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_playout: ^1.0.36
  flutter_secure_storage: ^3.3.5
  flutter_tts: ^0.8.5
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.5
  http: ^0.12.0+2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+14
  intl: ^0.16.0
  json_annotation: ^3.0.0
  just_audio: ^0.2.0
  meta: ^1.1.6
  path: ^1.7.0
  path_provider: ^1.6.11
  permission_handler: ^4.2.0+hotfix.3
  rxdart: ^0.24.1
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.3+1
  sqflite: ^1.1.7+1
  uuid: ^2.0.4
  flutter_rating_bar: ^3.2.0+1
  provider: ^4.3.2+3

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: ^1.3.1
  flutter_launcher_icons: ^0.8.1
  json_serializable: ^3.2.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aep_logo1.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/diamond.png
    - assets/images/african_echoes_logo.jpeg
    - assets/images/gmail_logo.png
    - assets/images/google_signin.png
    - assets/images/facebook_login.jpg
    - assets/images/categories.jpeg
    - assets/images/category.jpeg
    - assets/images/categories.png
    - assets/images/explore.jpeg
    - assets/images/home.jpeg
    - assets/images/aep_logo.jpeg
    - assets/images/splash.jpeg
    - assets/images/splash2.jpg
    - assets/images/splash3.jpg
    - assets/images/splash4.png
    - assets/images/splash3.jpg
    - assets/images/blank.png
    - assets/images/profile.jpeg
    - assets/images/airtel_tigo.png
    - assets/images/master.jpg
    - assets/images/mtn.jpg
    - assets/images/visa_card.png
    - assets/images/vodafone.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/6.jpg
    - assets/images/7.jpg
    - assets/images/8.jpg
    - assets/images/9.jpg
    - assets/images/10.jpg
    - assets/images/11.jpg
    - assets/images/12.jpg
    - assets/images/13.jpg
    - assets/images/14.jpg
    - assets/images/15.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-Light.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-BoldItalic.ttf
        - asset: fonts/Ubuntu-Italic.ttf
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-LightItalic.ttf
        - asset: fonts/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu-MediumItalic.ttf
        - asset: fonts/Ubuntu-Regular.ttf
  # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
